"""Rule-based decision: root cause to action plan.

Mirrors ``diagnosis.rules`` — the deterministic control arm, and the path taken
when the LLM is unavailable. Every plan it produces still passes through the
SafetyGate; being generated by code buys no exemption.
"""

from __future__ import annotations

from printpilot.domain import (
    FAULT_CATALOG,
    HARDWARE_BOUNDS,
    ActionPlan,
    ActionType,
    DiagnosisResult,
    FaultCode,
    ParamDelta,
    ParamName,
    ParamUnit,
    PhenomenonReport,
    RiskLevel,
)

#: Conservative single-step corrections. Small on purpose: a patch that fixes the
#: problem in one jump also breaks it in one jump if the diagnosis was wrong.
FLOW_STEP = 5.0
TEMP_STEP = 8.0


def _clamp(param: ParamName, delta: float) -> float:
    limit = HARDWARE_BOUNDS[param].max_abs_delta
    return max(-limit, min(limit, delta))


def decide(diagnosis: DiagnosisResult, report: PhenomenonReport) -> ActionPlan:
    fault = diagnosis.top.fault_code
    evidence = list(diagnosis.top.evidence)
    # risk_level is stated per branch rather than defaulted here: how dangerous an
    # action is, is the point of the branch, not a field to inherit.
    base = {"case_id": diagnosis.case_id, "evidence_refs": evidence}

    match fault:
        case FaultCode.CLOG_FULL:
            return ActionPlan(
                **base,
                action_type=ActionType.ABORT_PRINT,
                rationale=FAULT_CATALOG[fault].rationale,
                preconditions=["确认加热与运动已停止"],
                risk_level=RiskLevel.HIGH,
                requires_approval=True,
                rollback_plan="无需回滚；打印已中止，恢复前需完成喷嘴疏通。",
            )

        case FaultCode.CLOG_PARTIAL:
            return ActionPlan(
                **base,
                risk_level=RiskLevel.HIGH,
                action_type=ActionType.PAUSE_AND_INSPECT,
                rationale=FAULT_CATALOG[fault].rationale,
                preconditions=["暂停后保持热端温度以便检查", "不得在检查前恢复打印"],
                requires_approval=True,
                rollback_plan="检查未发现阻塞则恢复原参数继续打印。",
            )

        case FaultCode.UNDEREXT_PARAM:
            return ActionPlan(
                **base,
                risk_level=RiskLevel.MEDIUM,
                action_type=ActionType.APPLY_PARAM_PATCH,
                patch=[
                    ParamDelta(
                        param=ParamName.FLOW,
                        delta=_clamp(ParamName.FLOW, FLOW_STEP),
                        unit=ParamUnit.PERCENT,
                    )
                ],
                rationale="挤出量持续偏低而机械阻力正常，小幅提高 flow 补偿。",
                preconditions=["确认挤出机电流未升高"],
                requires_approval=False,
                rollback_plan=f"若流量未改善或电流上升，立即回退 flow {FLOW_STEP:g}%。",
            )

        case FaultCode.THERMAL_DRIFT:
            # Uses the *signed* bias. The absolute deviation was used first, which
            # is always positive, so the correction was always downward — wrong on
            # every case where the hot end was running cold.
            bias = report.feature("temp_bias_tail")
            direction = -1.0 if bias and bias.value > 0 else 1.0
            return ActionPlan(
                **base,
                risk_level=RiskLevel.MEDIUM,
                action_type=ActionType.APPLY_PARAM_PATCH,
                patch=[
                    ParamDelta(
                        param=ParamName.NOZZLE_TEMP,
                        delta=_clamp(ParamName.NOZZLE_TEMP, direction * TEMP_STEP),
                        unit=ParamUnit.CELSIUS,
                    )
                ],
                rationale="热端温度持续偏离设定值，调整设定以补偿偏差。",
                preconditions=["确认无机械阻力迹象"],
                requires_approval=False,
                rollback_plan=f"若温度偏差未收敛，回退 {TEMP_STEP:g}℃ 并转人工检查加热回路。",
            )

        case FaultCode.NORMAL_SUSPICIOUS:
            return ActionPlan(
                **base,
                risk_level=RiskLevel.LOW,
                action_type=ActionType.NO_ACTION,
                rationale="流量凹陷已恢复且无持续偏差，干预的风险高于收益。",
                requires_approval=False,
                rollback_plan="无变更，无需回滚。",
            )

        case _:
            return ActionPlan(
                **base,
                risk_level=RiskLevel.HIGH,
                action_type=ActionType.ESCALATE_TO_HUMAN,
                rationale="证据不足以支持任何具体根因；任何自动动作都预设了未被验证的前提。",
                preconditions=["提供缺失的判别信号后可重新诊断"],
                requires_approval=True,
                rollback_plan="无变更，无需回滚。",
            )
